import numpy as np
from log_likelihoods import Normal

class MultiFidelityProposal:
    """
    An empirical proposal distribution for Multi-Fidelity Sequential Monte Carlo (SMC).
    
    Instead of approximating the Low-Fidelity (LF) posterior with a parametric 
    distribution (like a Multivariate Normal), this class directly uses the 
    raw accepted particles from the LF SMC run as the proposal distribution 
    for the High-Fidelity (HF) run.
    
    Because the particles were generated by the LF model, their true underlying 
    probability density is proportional to the LF Posterior. Assuming a uniform 
    prior, the LF Posterior is directly proportional to the LF Likelihood. Thus, 
    the `logpdf` method evaluates and returns the LF log-likelihood.
    """

    def __init__(self, lofi_samples: np.ndarray, lofi_model, data: np.ndarray, noise_stdev: float):
        """
        Initializes the empirical Multi-Fidelity proposal distribution.

        Args:
            lofi_samples (np.ndarray): A 2D array of shape (N_particles, N_parameters) 
                containing the accepted posterior samples from the Low-Fidelity SMC run.
            lofi_model (callable): The Low-Fidelity model/function used to evaluate 
                the simulated outputs for given parameters.
            data (np.ndarray): The true observed measurement data being targeted.
            noise_stdev (float): The standard deviation of the Gaussian noise 
                associated with the measurement data.
        """
        self.lofi_samples = lofi_samples
        self.lofi_model = lofi_model
        self.noisy_data = data
        self.noise_stdev = noise_stdev

    def rvs(self, num_samples: int, random_state: int = None) -> np.ndarray:
        """
        Generates random samples directly from the Low-Fidelity posterior particles.

        If the requested number of samples matches the exact number of available 
        LF particles, it returns the entire set without shuffling. Otherwise, it 
        randomly subsets the particles without replacement.

        Args:
            num_samples (int): The number of particles/samples to propose for 
                the High-Fidelity run. Note: This cannot exceed the number of 
                available `lofi_samples` since replacement is set to False.
            random_state (int, optional): A seed for the random number generator 
                to ensure reproducibility across SMC runs. Defaults to None.

        Returns:
            np.ndarray: A 2D array of shape (num_samples, N_parameters) containing 
                the proposed particles.
        """
        # If asking for the exact number of particles we have, just return them all
        if num_samples == len(self.lofi_samples):
            return self.lofi_samples
            
        # Optional: handle the random state for reproducibility if smcpy passes one
        if random_state is not None:
            np.random.seed(random_state)

        # Randomly sample 'num_samples' rows without replacement
        random_indices = np.random.choice(self.lofi_samples.shape[0], size=num_samples, replace=False)
        
        return self.lofi_samples[random_indices]

    def logpdf(self, inputs: np.ndarray) -> np.ndarray:
        """
        Evaluates the proportional log probability density of the proposed particles.

        This calculates the log-likelihood of the inputs evaluated through the 
        Low-Fidelity model. Since the inputs were sampled from the LF posterior, 
        this Likelihood serves as the mathematically rigorous proposal density 
        `q(theta)` required by the SMC acceptance weight calculations.

        Args:
            inputs (np.ndarray): A 2D array of shape (num_samples, N_parameters) 
                representing the proposed parameter sets to be evaluated.

        Returns:
            np.ndarray: A 2D column array of shape (num_samples, 1) containing 
                the evaluated log-likelihood for each proposed particle.
        """
        # Instantiate the likelihood function for the LF model
        log_likelihood = Normal(self.lofi_model, self.noisy_data, self.noise_stdev)
        
        # Calculate the log-likelihood values for the given input particles
        log_L_values = log_likelihood(inputs)

        # Reshaping to (num_samples, 1) to ensure strict matrix shape compatibility
        # with standard SMC library internal weight calculations.
        return log_L_values.reshape(-1, 1)